### ISSUE TITLE
Page background gradient affects different parents depending on focus state

### ISSUE THREAD

**Issue by tymothy6** [tymothy6/ui-portfolio#4]
The `gradient:before` pseudo class (src/components/modules/landing.module.css) creates a transparent multi-colour gradient that is applied to the body of the landing (/) and blog (/blog) pages. It is also used to style the hero of the style guide, licenses, and resume pages. 

```css
.gradient:before {
  content: "";
  position: absolute;
  top: 0;
  background-image: radial-gradient(at 27% 37%, #3a8bfd 0, transparent 50%),
    radial-gradient(at 97% 21%, #9772fe 0, transparent 50%),
    radial-gradient(at 52% 99%, #fd3a4e 0, transparent 50%),
    radial-gradient(at 10% 29%, #5afc7d 0, transparent 50%),
    radial-gradient(at 97% 96%, #e4c795 0, transparent 50%),
    radial-gradient(at 33% 50%, #8ca8e8 0, transparent 50%),
    radial-gradient(at 79% 53%, #eea5ba 0, transparent 50%);
  width: 100vw;
  height: 100%;
  filter: blur(100px) saturate(150%);
  opacity: 0.1;
  z-index: -1;
}
```

When focus is trapped on interaction with a modal dialog or dropdown menu (`<Select />`, `<DropdownMenu />`, `<Dialog />`, etc.), the gradient is applied to the entire page rather than its respective container. This is only an issue on pages like /style and /resume where it should be constrained to the selected element.
